name: Deploy to Azure Container Instances

on:
  push:
    branches: [ test-ci ]

env:
  IMAGE_NAME: tixcraft-ocr-web
  CONTAINER_NAME: tixcraft-ocr-web-container
  RESOURCE_GROUP: dd-tixcraft-ocr-web_group
  LOCATION: eastasia

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        run: |
          az container delete --name $CONTAINER_NAME --resource-group $RESOURCE_GROUP --yes || true
          az container create \
            --resource-group $RESOURCE_GROUP \
            --name $CONTAINER_NAME \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --dns-name-label ${{ env.IMAGE_NAME }}-ci-cd-demo \
            --ports 80 \
            --location $LOCATION \
            --restart-policy Always
