name: Deploy to Azure Container Instances

on:
  push:
    branches: [ test-ci ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tixcraft-ocr-web:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tixcraft-ocr-web:${{ github.sha }}

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        run: |
          az container delete --name react-container --resource-group react-rg --yes || true
          az container create \
            --resource-group react-rg \
            --name react-container \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ github.sha }} \
            --dns-name-label react-app-ci-cd-demo \
            --ports 80 \
            --location eastasia \
            --restart-policy Always
